language: c

compiler:
  - gcc

script: make CFLAGS="-fPIC -Wall -Werror -std=gnu99 -g -O3 -Ibuild -I. -I/usr/lib/jvm/java-7-openjdk-amd64/include/ -I/usr/lib/jvm/java-7-openjdk-amd64/include/linux/ -Ibuild"
