language: c

compiler:
  - gcc

script: make CFLAGS="-fPIC -Wall -Werror -std=gnu99 -g -O3 -Ibuild -I. -I/usr/lib/jvm/java-7-openjdk-*/include/ -I/usr/lib/jvm/java-7-openjdk-*/include/linux/ -Ibuild"
